### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by MclaughlinSteve**
Testing code climate integration

Pulled some common logic out into a function

### CODE REVIEW

**Comment by MergeBot9000** [comment]
Uh oh! It looks like there was a problem trying to automerge this pull request.

It seems likely that this is due to a cancelled or failing status check. Take a look at your statuses and
 get them passing before reapplying the automerge label.

**Comment by MergeBot9000** [comment]
Uh oh! It looks like there was a problem trying to automerge this pull request.

It seems likely that this is due to a cancelled or failing status check. Take a look at your statuses and
 get them passing before reapplying the automerge label.

**Comment by MclaughlinSteve** [comment]
Just verifying that I uploaded the newest version to lambda

**Comment by MergeBot9000** [comment]
Uh oh! It looks like there was a problem trying to automerge this pull request.

It seems likely that this is due to a cancelled or failing status check. Take a look at your statuses and
 get them passing before reapplying the automerge label.

**Pull request merged**
